name: Push development branch

on:
  push:
    branches:
      - develop

jobs:
  push-dev:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Print
        run: |
          echo "Log: develop branch"