name: Triggered by push dev event

on:
  workflow_run:
    workflows: [Push development branch]
    branches: [develop]
    types:
      - completed

jobs:
  workflow-run:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Workflow_run happens"